name: second_github_action
on: [push]
jobs:
  aws_cp:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAVRUVSF6E7XZB6MBW
          aws-secret-access-key: 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
          aws-region: us-east-2
      - name: Upload to s3
        run: aws s3 cp ./README.md s3://s3githubactionsetl
