name: glue_deployment
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  aws_cp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAVRUVSF6EYIODMMV4
          aws-secret-access-key: 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
          aws-region: us-east-2
      - name: Upload the Glue code to s3
        run: |
          aws s3 cp ./csv_to_parquet.py s3://aws-glue-assets-381492014985-us-east-2/scripts/
